// Auto-generated by AudioReferencesGenerator
using System.Collections;
using UnityEngine;

public static partial class R
{
    public static class Audio
    {
    }

    public static IEnumerator LoadAudioClips()
    {
        yield return null;
    }
}
